name: deploy-model-training-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml
  
  create-compute:
      needs: get-config
      uses: ./.github/workflows/custom-create-compute.yml
      with:
        cluster_name: test-cluster
        size: Standard_DS11_v2
        min_instances: 0
        max_instances: 1
        cluster_tier: dedicated
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
      # secrets:
        # AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        # AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        # AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}} 
        
  register-dataset:
    needs: get-config
    uses: ./.github/workflows/custom-register-dataset.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: machine-failure-data
      data_file: mlops/azureml/train/data.yml
    # secrets:
    #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  
  register-environment:
      needs: get-config
      uses: ./.github/workflows/custom-register-environment.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file:  mlops/azureml/train/train-env.yml
        conda_file: data-science/environment/train-conda.yml
      # secrets:
      #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
  run-pipeline:
      needs: [get-config,register-environment,create-compute,register-dataset]
      uses: ./.github/workflows/custom-run-pipeline.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        parameters-file:  mlops/azureml/train/newpipeline.yml
        job-name: mlops-pipeline
      # secrets:
      #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
